use  [EJERCICIO_5]
 
INSERT INTO [dbo].[Rubro] ([NombRubro]) VALUES ('Policial')
INSERT INTO [dbo].[Rubro] ([NombRubro]) VALUES ('Acción')
INSERT INTO [dbo].[Rubro] ([NombRubro]) VALUES ('Aventuras')
INSERT INTO [dbo].[Rubro] ([NombRubro]) VALUES ('Comedias')
INSERT INTO [dbo].[Rubro] ([NombRubro]) VALUES ('Dramáticas')
INSERT INTO [dbo].[Rubro] ([NombRubro]) VALUES ('Terror')
INSERT INTO [dbo].[Rubro] ([NombRubro]) VALUES ('Musicales')
INSERT INTO [dbo].[Rubro] ([NombRubro]) VALUES ('Ciencia ficción')
INSERT INTO [dbo].[Rubro] ([NombRubro]) VALUES ('Suspenso')


--
INSERT INTO [dbo].[Cliente] ([Nombre], [Apellido], [Direccion], [Tel], [Email]) VALUES ('Nombre1','Apellido1','Direccion1','Tel1','email1')  
INSERT INTO [dbo].[Cliente] ([Nombre], [Apellido], [Direccion], [Tel], [Email]) VALUES ('Nombre2','Apellido2','Direccion2','Tel2','email2')
INSERT INTO [dbo].[Cliente] ([Nombre], [Apellido], [Direccion], [Tel], [Email]) VALUES ('Nombre3','Apellido3','Direccion3','Tel3','email3')
INSERT INTO [dbo].[Cliente] ([Nombre], [Apellido], [Direccion], [Tel], [Email]) VALUES ('Nombre4','Apellido4','Direccion4','Tel4','email4')
INSERT INTO [dbo].[Cliente] ([Nombre], [Apellido], [Direccion], [Tel], [Email]) VALUES ('Nombre5','Apellido5','Direccion5','Tel5','email5')
INSERT INTO [dbo].[Cliente] ([Nombre], [Apellido], [Direccion], [Tel], [Email]) VALUES ('Nombre6','Apellido6','Direccion6','Tel6','email6')
INSERT INTO [dbo].[Cliente] ([Nombre], [Apellido], [Direccion], [Tel], [Email]) VALUES ('Nombre7','Apellido7','Direccion7','Tel7','email7')
INSERT INTO [dbo].[Cliente] ([Nombre], [Apellido], [Direccion], [Tel], [Email]) VALUES ('Nombre8','Apellido8','Direccion8','Tel8','email8')
INSERT INTO [dbo].[Cliente] ([Nombre], [Apellido], [Direccion], [Tel], [Email]) VALUES ('Nombre9','Apellido9','Direccion9','Tel9','email9')
INSERT INTO [dbo].[Cliente] ([Nombre], [Apellido], [Direccion], [Tel], [Email]) VALUES ('Nombre10','Apellido10','Direccion10','Tel10','email10')
INSERT INTO [dbo].[Cliente] ([Nombre], [Apellido], [Direccion], [Tel], [Email]) VALUES ('Nombre11','Apellido11','Direccion11','Tel11','email11')
INSERT INTO [dbo].[Cliente] ([Nombre], [Apellido], [Direccion], [Tel], [Email]) VALUES ('Nombre12','Apellido12','Direccion12','Tel12','email12')
INSERT INTO [dbo].[Cliente] ([Nombre], [Apellido], [Direccion], [Tel], [Email]) VALUES ('Nombre13','Apellido13','Direccion13','Tel13','email13')
INSERT INTO [dbo].[Cliente] ([Nombre], [Apellido], [Direccion], [Tel], [Email]) VALUES ('Nombre14','Apellido14','Direccion14','Tel14','email14')
INSERT INTO [dbo].[Cliente] ([Nombre], [Apellido], [Direccion], [Tel], [Email]) VALUES ('Nombre15','Apellido15','Direccion15','Tel15','email15')


INSERT INTO [dbo].[Pelicula] ( [Titulo], [Duracion], [Anio], [CodRubro]) VALUES ('Buscando a Nemo',3,2003,1)
INSERT INTO [dbo].[Pelicula] ( [Titulo], [Duracion], [Anio], [CodRubro]) VALUES ('Ciudad de Dios',30,2002,2)
INSERT INTO [dbo].[Pelicula] ( [Titulo], [Duracion], [Anio], [CodRubro]) VALUES ('Hable con ella',1,2002,3)
INSERT INTO [dbo].[Pelicula] ( [Titulo], [Duracion], [Anio], [CodRubro]) VALUES ('El Señor de los Anilllos',60,2001,4)
INSERT INTO [dbo].[Pelicula] ( [Titulo], [Duracion], [Anio], [CodRubro]) VALUES ('Kandahar ',20,2001,5)
INSERT INTO [dbo].[Pelicula] ( [Titulo], [Duracion], [Anio], [CodRubro]) VALUES ('La mirada de Ulises',4,1995,6)
INSERT INTO [dbo].[Pelicula] ( [Titulo], [Duracion], [Anio], [CodRubro]) VALUES ('Pulp Fiction',1.5,1994,7)
INSERT INTO [dbo].[Pelicula] ( [Titulo], [Duracion], [Anio], [CodRubro]) VALUES ('Adiós a mi concubina',3,1993,8)
INSERT INTO [dbo].[Pelicula] ( [Titulo], [Duracion], [Anio], [CodRubro]) VALUES ('Rey León',2,1994,9)
INSERT INTO [dbo].[Pelicula] ( [Titulo], [Duracion], [Anio], [CodRubro]) VALUES ('Terminador 3',2.5,2003,1)
INSERT INTO [dbo].[Pelicula] ( [Titulo], [Duracion], [Anio], [CodRubro]) VALUES ('El Padrino',6,1972,2)
INSERT INTO [dbo].[Pelicula] ( [Titulo], [Duracion], [Anio], [CodRubro]) VALUES ('E.T. El extraterrestre',6,1982,3)


INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (1,1,0,'A1')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (2,1,1,'A2')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (3,1,1,'A3')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (1,2,0,'A1')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (2,2,1,'A2')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (3,2,1,'A3')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (1,3,0,'A1')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (2,3,1,'A2')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (3,3,1,'A3')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (1,4,0,'A1')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (2,4,1,'A2')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (3,4,1,'A3')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (1,5,0,'A1')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (2,5,1,'A2')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (3,5,1,'A3')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (1,6,0,'A1')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (2,6,1,'A2')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (3,6,1,'A3')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (1,7,0,'A1')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (2,7,1,'A2')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (3,7,1,'A3')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (1,8,0,'A1')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (2,8,1,'A2')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (3,8,1,'A3')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (1,9,0,'A1')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (2,9,1,'A2')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (3,9,1,'A3')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (1,10,0,'A1')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (2,10,1,'A2')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (3,10,1,'A3')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (1,11,0,'A1')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (2,11,1,'A2')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (3,11,1,'A3')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (1,12,0,'A1')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (2,12,1,'A2')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (3,12,1,'A3')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (4,1,0,'A1')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (4,2,1,'A2')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (4,3,1,'A3')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (4,4,0,'A1')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (4,5,1,'A2')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (4,6,1,'A3')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (5,1,0,'A1')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (6,1,1,'A2')
INSERT INTO [dbo].[Ejemplar] ([CodEj], [CodPel], [Estado], [Ubicación]) VALUES (7,1,1,'A3')




INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (1,1,1,'2019-01-01','2019-01-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (1,1,1,'2019-04-01','2019-04-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (1,2,2,'2019-05-01','2019-05-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (1,3,3,'2019-06-01','2019-06-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (1,4,2,'2019-01-02',NULL)
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (1,5,5,'2019-04-02','2019-04-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (1,6,6,'2019-05-02','2019-05-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (1,7,9,'2019-06-02','2019-06-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (1,8,7,'2019-01-03','2019-01-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (1,9,6,'2019-04-03','2019-04-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (1,10,9,'2019-05-03','2019-05-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (1,11,8,'2019-06-03','2019-06-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (2,1,10,'2019-01-04','2019-01-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (2,2,11,'2019-04-04','2019-04-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (2,3,12,'2019-05-04','2019-05-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (2,4,13,'2019-06-04','2019-06-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (2,5,14,'2019-01-05','2019-01-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (2,6,15,'2019-04-05','2019-04-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (2,7,1,'2019-05-05',NULL)
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (2,8,2,'2019-06-05','2019-06-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (2,9,3,'2019-01-06','2019-01-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (2,10,7,'2019-04-06','2019-04-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (2,11,4,'2019-05-06','2019-05-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (3,1,5,'2019-06-06','2019-06-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (3,2,6,'2019-01-07','2019-01-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (3,3,8,'2019-04-07','2019-04-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (3,4,9,'2019-01-02','2019-01-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (3,5,10,'2019-04-02','2019-04-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (3,6,11,'2019-05-02','2019-05-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (3,7,5,'2019-06-02','2019-06-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (3,8,5,'2019-01-03','2019-01-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (3,9,5,'2019-04-03','2019-04-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (3,10,5,'2019-05-03','2019-05-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (3,11,5,'2019-06-03',NULL)
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (4,1,4,'2019-01-04','2019-01-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (4,2,5,'2019-04-04','2019-04-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (4,3,5,'2019-05-04','2019-05-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (4,4,5,'2019-06-04','2019-06-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (4,5,4,'2019-01-05','2019-01-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (4,6,5,'2019-04-05','2019-04-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (5,1,12,'2019-05-05',NULL)
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (6,1,13,'2019-06-05','2019-06-03')
INSERT INTO [dbo].[Prestamo] ( [CodEj], [CodPel], [CodCli], [FechaPrest], [FechaDev]) VALUES (7,1,14,'2019-01-06','2019-01-03')
